version: "3"
services:

  nginx:
    container_name: nginx
    build: ./DockerConfigs/Nginx
    ports:
      - 80:80
      - 443:443
    network_mode: bridge


  nodejs:
    container_name: nodejs
    build: .\DockerConfigs\Nodejs
    volumes:
      - ./Nodejs:/var/www/node
      #- ./Nodejs:/var/www/node
    command: bash      #npm run nf
    tty: true # Only for Dev
    environment:
      PORT: 3000 # process.env.PORT
    network_mode: bridge

  redis:
    container_name: redis
    build: ./DockerConfigs/Redis
    network_mode: bridge

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - SeniorProject_MongoDB_Data:/data/db
    ports:
      - 27017:27017
    command: bash
    tty: true
    network_mode: bridge


volumes:
  SeniorProject_MongoDB_Data: {}